export const GET_ALLUSERS_REQUEST = 'GET_ALLUSERS_REQUEST';
export const GET_ALLUSERS_SUCCESS = 'GET_ALLUSERS_SUCCESS';
export const GET_ALLUSERS_FAIL = 'GET_ALLUSERS_FAIL';

export const GET_SUGGESTION_REQUEST = 'GET_SUGGESTION_REQUEST';
export const GET_SUGGESTION_SUCCESS = 'GET_SUGGESTION_SUCCESS';
export const GET_SUGGESTION_FAIL = 'GET_SUGGESTION_FAIL';

export const GET_TRAVELDETAILS_REQUEST = 'GET_TRAVELDETAILS_REQUEST';
export const GET_TRAVELDETAILS_SUCCESS = 'GET_TRAVELDETAILS_SUCCESS';
export const GET_TRAVELDETAILS_FAIL = 'GET_TRAVELDETAILS_FAIL';

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';

export const DELETE_SUGGESTION_REQUEST = 'DELETE_SUGGESTION_REQUEST';
export const DELETE_SUGGESTION_SUCCESS = 'DELETE_SUGGESTION_SUCCESS';
export const DELETE_SUGGESTION_FAIL = 'DELETE_SUGGESTION_FAIL';

export const DELETE_TRAVELDETAILS_REQUEST = 'DELETE_TRAVELDETAILS_REQUEST';
export const DELETE_TRAVELDETAILS_SUCCESS = 'DELETE_TRAVELDETAILS_SUCCESS';
export const DELETE_TRAVELDETAILS_FAIL = 'DELETE_TRAVELDETAILS_FAIL';

export const DELETE_ADMIN_RESET = 'DELETE_ADMIN_RESET';
