export const CREATE_TRAVEL_REQUEST = 'CREATE_TRAVEL_REQUEST';
export const CREATE_TRAVEL_SUCCESS = 'CREATE_TRAVEL_SUCCESS';
export const CREATE_TRAVEL_FAIL = 'CREATE_TRAVEL_FAIL';

export const GET_TRAVELDETAILS_REQUEST = 'GET_TRAVELDETAILS_REQUEST';
export const GET_TRAVELDETAILS_SUCCESS = 'GET_TRAVELDETAILS_SUCCESS';
export const GET_TRAVELDETAILS_FAIL = 'GET_TRAVELDETAILS_FAIL';

export const DELETE_TRAVELDETAILS_REQUEST = 'DELETE_TRAVELDETAILS_REQUEST';
export const DELETE_TRAVELDETAILS_SUCCESS = 'DELETE_TRAVELDETAILS_SUCCESS';
export const DELETE_TRAVELDETAILS_FAIL = 'DELETE_TRAVELDETAILS_FAIL';

export const DELETE_TRAVELDETAILS_RESET = 'DELETE_TRAVELDETAILS_RESET';
